### ISSUE TITLE
Bug: Opensea pushing high price listings

### ISSUE THREAD

**Issue by IkigaiLabsETH** [IkigaiLabsETH/ikigailabs.xyz#130]
![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/3e08af6b-3c72-4d3d-90f3-e20a91b9c559)
![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/b4c7e0ee-12c2-4180-8167-1f49299c1797)
![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/bfffbb37-fe15-4464-92a9-a3c7852f7fe6)

GM, think we will need to flag this with Reservoir Tools, but discovered (on X user feedback) that I see for example a cheap Ringers on Floor, I click and see a much higher price only to discover that there is indeed a listing at 14 ETH

**Comment by royscheeren** [comment]
Could this be because price is listing + fees,

Where the listings is just the listing pricE?
