### ISSUE TITLE
Fix: Editions in My Profile

### ISSUE THREAD

**Issue by IkigaiLabsETH** [IkigaiLabsETH/ikigailabs.xyz#136]
![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/93b35aa2-ff43-4cbc-af4b-e7fb364d903b)

**Comment by royscheeren** [comment]
What's the bug? 


![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/1575680/24ebb180-5451-485f-9f64-2b697f896fc5)

**Comment by IkigaiLabsETH** [comment]
I see no bug, it show owned numba and total numba edition.
