### ISSUE TITLE
Bug: Success Modal URL artio nft

### ISSUE THREAD

**Issue by IkigaiLabsETH** [IkigaiLabsETH/ikigailabs.xyz#80]
![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/ebf42b74-fb09-447f-8ed3-cd15db4224a5)

the claim worked, but the success modal stopped working, as in it keeps spinning on the button, and although transaction is confirmed and NFT is minted onchain, the success modal does not pop up

**Comment by royscheeren** [comment]
@IkigaiLabsETH Can you please try that again when bera is operating properly, it will happen if the chain is too slow and doesnt provide an answer within 30 seconds or so. (TW settings). 

The transaction will eventually complete, but the site will stop listening.

**Comment by IkigaiLabsETH** [comment]
the url for the artio explore has an NFT dedicate  url like https://artio.beratrail.io/nft/0x986407BAfcb7323808d13573074F243ee7A2cc3c/7#metadata

would be good to use that one on the (dynamic) success modal link
