### ISSUE TITLE
Bug: Mint Multiple NFTs on B/ERA

### ISSUE THREAD

**Issue by IkigaiLabsETH** [IkigaiLabsETH/ikigailabs.xyz#90]
try minting multiple NFTs on bera, there seems to be a bug

![Image](https://github.com/IkigaiLabsETH/ikigailabs.xyz/assets/128307722/05523217-c694-4ba8-83b7-367ad04713ff)

**Comment by royscheeren** [comment]
Unable to reproduce:

https://artio.beratrail.io/tx/0x6ee144e83a8a27029b7f190e4e9e1acf1d5aea426d3aceec2d5a7b1db4e447d3

**Comment by IkigaiLabsETH** [comment]
same, unable to reproduce
